[id="starknet-react"]

= Starknet React

Developed by the https://github.com/apibara/[Apibara] team, https://github.com/apibara/starknet-react/[Starknet React] is an open-source  collection of React providers and hooks for Starknet, inspired by https://github.com/tmm/wagmi/[wagmi]. If you've used wagmi before, you  should have a pretty good idea of what it looks like, as it aims to have a very similar API.

To begin using Starknet React, start by installing the necessary dependencies:

```
yarn add @starknet-react/core starknet get-starknet
```

[NOTE]
====
https://www.starknetjs.com/[Starknet.js] is an essential low level lib for interacting with Starknet, whereas https://github.com/starknet-io/get-starknet/[get-starknet] is a package for handling wallet connections that Starknet React depends on.
====

Then, wrap your app in a `StarknetConfig` component. This allows for some configuration and provides a React Context to the underlying app to be able to use the shared  data and hooks:

```ts
const connectors = [
  new InjectedConnector({ options: { id: "braavos" } }),
  new InjectedConnector({ options: { id: "argentX" } }),
];

return (
    <StarknetConfig
      connectors={connectors}
      // defaultProvider={...}
      // autoConnect={false}
    >
      <App />
    </StarknetConfig>
)
```

You can now use the hooks to access the connectors you defined in the config, allowing the user to connect their wallet:

```ts
export default function Connect() {
  const { connect, connectors } = useConnectors();

  return (
    <div>
      {connectors.map((connector) => (
        <button
          key={connector.id()}
          onClick={() => connect(connector)}
          disabled={!connector.available()}
        >
          Connect with {connector.id()}
        </button>
      ))}
    </div>
  );
}
```

Once the user has connected their wallet, you have access to the connected account through the `useAccount` hook. This also providdes the current state of connection:

```ts
const { address, isConnected, isReconnecting, account } = useAccount();

return (
    <div>
      {isConnected ? (
          <p>Hello, {address}</p>          
      ) : (
        <Connect />
      )}
    </div>
);
```

Note that state values such as `isConnected` and `isReconnecting` are updated automatically, making it easier to update the UI conditionally. This is a very useful and common pattern when dealing with asynchronous processes, as it means you don't have to keep track of that state locally in your components.

Starknet React also provides hooks for interacting with the provider. For instance, `useBlock` fetches the latest block:

```ts
const { data, isError, isFetching } = useBlock({
    refetchInterval: 10_000,
    blockIdentifier: "latest",
});

if (isError) {
  return (
    <p>Something went wrong</p>
  )
}

return (
    <p>Current block: {isFetching ? "Loading..." : data?.block_number}<p>
)
```

The `refetchInterval` specifies how often the hook will attempt to refetch the data.  Under the hood, Starknet React uses https://github.com/TanStack/query/[react-query] for state  and query management. Besides `useBlock`, there are other hooks that can be configured to periodically update, such as `useContractRead` and `useWaitForTransaction`.

## Interacting with contracts

### Read functions
Just like with wagmi, there is a `useContractRead` hook provided specifically for calling read functions on contracts. Note that this may be used even with without a connected user, as read functions don't require a signer.

```ts
const { data: balance, isLoading, isError, isSuccess } = useContractRead({
    abi: abi_erc20,
    address: CONTRACT_ADDRESS,
    functionName: "balanceOf",
    args: [address],
    // watch: true <- refresh at every block
});
```

### Write functions
For write functions, the `useContractWrite` hook is slightly different to wagmi. Due  to Starknet's architecture, accounts can natively support multicall transactions. In practice, this means an  improved user experience when executing multiple transactions, as you won't have to individually approve each transaction. Therefore  it makes sense that starknet-react should make  the most of this feature. It can be used in the following manner:

```ts
const calls = useMemo(() => {
    // compile the calldata to send
    const calldata = stark.compileCalldata({
      argName: argValue,
    });

    // return a single object for single transaction, 
    // or an array of objects for multicall
    return {
      contractAddress: CONTRACT_ADDRESS,
      entrypoint: functionName,
      calldata,
    };        
}, [argValue]);

const { write, isLoading, data } = useContractWrite({
    calls,
});

function execute() {
  // trigger the transaction
  write();
}

return (
  <button type="button" onClick={execute}>
    Make a transaction
  </button>
)
```

In the example above, we first compile the calldata to be executed and pass that to the `useContractWrite` hook, which returns a `write` function we can use to actually trigger it. The hook alo returns the state and result of the contract call.

### Single instance

Using `useContractRead` and `useContractWrite` might not a good fit for your use case - you might want to work with a single instance of the contract, instead of continually specifying its address and ABI in individual hooks. This is also possible throught the `useContract` hook:

```ts
const { contract } = useContract({
    address: CONTRACT_ADDRESS,
    abi: abi_erc20,
});

// contract.transfer(...);
// contract.balanceOf(...);
```


To explore an example project, visit [here](https://github.com/apibara/starknet-react/tree/main/website).


== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
